commerce_facebook_catalog.settings:
  type: config_object
  label: 'Facebook Catalog'
  mapping:
    facebook_catalog_enabled:
      type: boolean
      label: 'Enable Facebook Catalog'
    what_to_include:
      type: sequence
      sequence:
        type: string
      label: 'What to include?'
    brand:
      type: string
      label: 'Brand name'
